language: csharp
sudo: required
dotnet: 2.0.0
os:  
  - linux
branches:  
  only:
    - master
services:
  - docker
before_install:
  - cd SoftPlc
script:
  - dotnet publish -c release -o release
  - cp ./native/linux/libsnap7.so ./release/libsnap7.so
  - cp ./Docker/linux-x64/Dockerfile ./release/Dockerfile
  - cd release
  - docker build -t fbarresi/softplc:1.0beta$TRAVIS_BUILD_NUMBER-linux .
  - rm libsnap7.so
  - rm Dockerfile
  - cd ..
  - cp ./native/win/snap7.dll ./release/snap7.dll
  - cp ./Docker/windows-nano/Dockerfile ./release/Dockerfile
  - cd release
  - docker build -t fbarresi/softplc:1.0beta$TRAVIS_BUILD_NUMBER-win .
#  - docker run --name softplc fbarresi/softplc:1.0beta$TRAVIS_BUILD_NUMBER-linux
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push fbarresi/softplc:1.0beta$TRAVIS_BUILD_NUMBER-linux;
  - docker push fbarresi/softplc:1.0beta$TRAVIS_BUILD_NUMBER-win;
