sudo: required
services:
  - docker
before_install:
  - cd SoftPlc
  - docker build -t cinhtau/elasticsearch .
script:
  - docker images cinhtau/elasticsearch
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push cinhtau/elasticsearch;
    fi
